"""empty message

Revision ID: fee6f54dfd0d
Revises:
Create Date: 2026-02-25 19:59:25.981014

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "fee6f54dfd0d"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "employee_enrollment",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=False),
        sa.Column("employee_id", sa.Integer(), nullable=False),
        sa.Column("matricula", sa.Text(), nullable=False),
        sa.Column("active_from", sa.Date(), nullable=False),
        sa.Column("active_to", sa.Date(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_employee_enrollment_employee_id"),
        "employee_enrollment",
        ["employee_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_employee_enrollment_tenant_id"),
        "employee_enrollment",
        ["tenant_id"],
        unique=False,
    )
    op.create_table(
        "work_policy_template",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("daily_work_minutes", sa.Integer(), nullable=False),
        sa.Column("break_minutes", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_work_policy_template_tenant_id"),
        "work_policy_template",
        ["tenant_id"],
        unique=False,
    )
    op.create_table(
        "bank_hours_ledger",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=False),
        sa.Column("enrollment_id", sa.Integer(), nullable=False),
        sa.Column("event_date", sa.Date(), nullable=False),
        sa.Column("minutes_delta", sa.Integer(), nullable=False),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("reference_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["enrollment_id"],
            ["employee_enrollment.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "daily_attendance_summary",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=False),
        sa.Column("enrollment_id", sa.Integer(), nullable=False),
        sa.Column("work_date", sa.Date(), nullable=False),
        sa.Column("expected_minutes", sa.Integer(), nullable=False),
        sa.Column("worked_minutes", sa.Integer(), nullable=False),
        sa.Column("break_minutes", sa.Integer(), nullable=False),
        sa.Column("overtime_minutes", sa.Integer(), nullable=False),
        sa.Column("deficit_minutes", sa.Integer(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["enrollment_id"],
            ["employee_enrollment.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "enrollment_policy_assignment",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=False),
        sa.Column("enrollment_id", sa.Integer(), nullable=False),
        sa.Column("template_id", sa.Integer(), nullable=False),
        sa.Column("effective_from", sa.Date(), nullable=False),
        sa.Column("effective_to", sa.Date(), nullable=True),
        sa.ForeignKeyConstraint(
            ["enrollment_id"],
            ["employee_enrollment.id"],
        ),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["work_policy_template.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "time_adjustment_request",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=False),
        sa.Column("enrollment_id", sa.Integer(), nullable=False),
        sa.Column("request_date", sa.Date(), nullable=False),
        sa.Column("type", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=False),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("decided_by", sa.Integer(), nullable=True),
        sa.Column("decision_reason", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["enrollment_id"],
            ["employee_enrollment.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "time_punch",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=False),
        sa.Column("enrollment_id", sa.Integer(), nullable=False),
        sa.Column("punched_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("punch_type", sa.Text(), nullable=False),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["enrollment_id"],
            ["employee_enrollment.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "time_adjustment_item",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=False),
        sa.Column("request_id", sa.Integer(), nullable=False),
        sa.Column("proposed_punch_type", sa.Text(), nullable=True),
        sa.Column("proposed_punched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("original_punch_id", sa.Integer(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["original_punch_id"],
            ["time_punch.id"],
        ),
        sa.ForeignKeyConstraint(
            ["request_id"],
            ["time_adjustment_request.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("time_adjustment_item")
    op.drop_table("time_punch")
    op.drop_table("time_adjustment_request")
    op.drop_table("enrollment_policy_assignment")
    op.drop_table("daily_attendance_summary")
    op.drop_table("bank_hours_ledger")
    op.drop_index(
        op.f("ix_work_policy_template_tenant_id"), table_name="work_policy_template"
    )
    op.drop_table("work_policy_template")
    op.drop_index(
        op.f("ix_employee_enrollment_tenant_id"), table_name="employee_enrollment"
    )
    op.drop_index(
        op.f("ix_employee_enrollment_employee_id"), table_name="employee_enrollment"
    )
    op.drop_table("employee_enrollment")
    # ### end Alembic commands ###
