"""empty message

Revision ID: c191d406a9df
Revises:
Create Date: 2026-02-27 15:47:26.601780

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c191d406a9df"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bank_hours_ledger",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=False),
        sa.Column("employee_id", sa.Integer(), nullable=False),
        sa.Column("matricula", sa.Text(), nullable=False),
        sa.Column("event_date", sa.Date(), nullable=False),
        sa.Column("minutes_delta", sa.Integer(), nullable=False),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("reference_id", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_bank_hours_ledger_employee_id"),
        "bank_hours_ledger",
        ["employee_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_bank_hours_ledger_matricula"),
        "bank_hours_ledger",
        ["matricula"],
        unique=False,
    )
    op.create_index(
        op.f("ix_bank_hours_ledger_tenant_id"),
        "bank_hours_ledger",
        ["tenant_id"],
        unique=False,
    )
    op.create_table(
        "daily_attendance_summary",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=False),
        sa.Column("employee_id", sa.Integer(), nullable=False),
        sa.Column("matricula", sa.Text(), nullable=False),
        sa.Column("work_date", sa.Date(), nullable=False),
        sa.Column("expected_minutes", sa.Integer(), nullable=False),
        sa.Column("worked_minutes", sa.Integer(), nullable=False),
        sa.Column("break_minutes", sa.Integer(), nullable=False),
        sa.Column("overtime_minutes", sa.Integer(), nullable=False),
        sa.Column("deficit_minutes", sa.Integer(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_daily_attendance_summary_employee_id"),
        "daily_attendance_summary",
        ["employee_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_daily_attendance_summary_matricula"),
        "daily_attendance_summary",
        ["matricula"],
        unique=False,
    )
    op.create_index(
        op.f("ix_daily_attendance_summary_tenant_id"),
        "daily_attendance_summary",
        ["tenant_id"],
        unique=False,
    )
    op.create_table(
        "holiday_calendar",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("city", sa.Text(), nullable=True),
        sa.Column("uf", sa.Text(), nullable=True),
        sa.Column("effective_from", sa.Date(), nullable=False),
        sa.Column("effective_to", sa.Date(), nullable=False),
        sa.Column("national", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_holiday_calendar_tenant_id"),
        "holiday_calendar",
        ["tenant_id"],
        unique=False,
    )
    op.create_table(
        "time_adjustment_request",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=False),
        sa.Column("employee_id", sa.Integer(), nullable=False),
        sa.Column("matricula", sa.Text(), nullable=False),
        sa.Column("request_date", sa.Date(), nullable=False),
        sa.Column("type", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=False),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("decided_by", sa.Integer(), nullable=True),
        sa.Column("decision_reason", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_time_adjustment_request_employee_id"),
        "time_adjustment_request",
        ["employee_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_time_adjustment_request_matricula"),
        "time_adjustment_request",
        ["matricula"],
        unique=False,
    )
    op.create_index(
        op.f("ix_time_adjustment_request_tenant_id"),
        "time_adjustment_request",
        ["tenant_id"],
        unique=False,
    )
    op.create_table(
        "time_punch",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=False),
        sa.Column("employee_id", sa.Integer(), nullable=False),
        sa.Column("matricula", sa.Text(), nullable=False),
        sa.Column("punched_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("punch_type", sa.Text(), nullable=False),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_time_punch_employee_id"), "time_punch", ["employee_id"], unique=False
    )
    op.create_index(
        op.f("ix_time_punch_matricula"), "time_punch", ["matricula"], unique=False
    )
    op.create_index(
        op.f("ix_time_punch_tenant_id"), "time_punch", ["tenant_id"], unique=False
    )
    op.create_table(
        "work_policy_template",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_work_policy_template_tenant_id"),
        "work_policy_template",
        ["tenant_id"],
        unique=False,
    )
    op.create_table(
        "employee_holiday_calendar_assignment",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("employee_id", sa.Integer(), nullable=False),
        sa.Column("holiday_calendar_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["holiday_calendar_id"],
            ["holiday_calendar.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_employee_holiday_calendar_assignment_employee_id"),
        "employee_holiday_calendar_assignment",
        ["employee_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_employee_holiday_calendar_assignment_holiday_calendar_id"),
        "employee_holiday_calendar_assignment",
        ["holiday_calendar_id"],
        unique=False,
    )
    op.create_table(
        "enrollment_policy_assignment",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=False),
        sa.Column("employee_id", sa.Integer(), nullable=False),
        sa.Column("matricula", sa.Text(), nullable=False),
        sa.Column("template_id", sa.Integer(), nullable=False),
        sa.Column("effective_from", sa.Date(), nullable=False),
        sa.Column("effective_to", sa.Date(), nullable=True),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["work_policy_template.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_enrollment_policy_assignment_employee_id"),
        "enrollment_policy_assignment",
        ["employee_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_enrollment_policy_assignment_matricula"),
        "enrollment_policy_assignment",
        ["matricula"],
        unique=False,
    )
    op.create_index(
        op.f("ix_enrollment_policy_assignment_tenant_id"),
        "enrollment_policy_assignment",
        ["tenant_id"],
        unique=False,
    )
    op.create_table(
        "holiday",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("holiday_calendar_id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["holiday_calendar_id"],
            ["holiday_calendar.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_holiday_holiday_calendar_id"),
        "holiday",
        ["holiday_calendar_id"],
        unique=False,
    )
    op.create_table(
        "time_adjustment_item",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=False),
        sa.Column("request_id", sa.Integer(), nullable=False),
        sa.Column("proposed_punch_type", sa.Text(), nullable=True),
        sa.Column("proposed_punched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("original_punch_id", sa.Integer(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["original_punch_id"],
            ["time_punch.id"],
        ),
        sa.ForeignKeyConstraint(
            ["request_id"],
            ["time_adjustment_request.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "work_day_policy",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("work_policy_template_id", sa.Integer(), nullable=False),
        sa.Column("daily_work_minutes", sa.Integer(), nullable=False),
        sa.Column("break_minutes", sa.Integer(), nullable=False),
        sa.Column("week_day", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["work_policy_template_id"],
            ["work_policy_template.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_work_day_policy_work_policy_template_id"),
        "work_day_policy",
        ["work_policy_template_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_work_day_policy_work_policy_template_id"), table_name="work_day_policy"
    )
    op.drop_table("work_day_policy")
    op.drop_table("time_adjustment_item")
    op.drop_index(op.f("ix_holiday_holiday_calendar_id"), table_name="holiday")
    op.drop_table("holiday")
    op.drop_index(
        op.f("ix_enrollment_policy_assignment_tenant_id"),
        table_name="enrollment_policy_assignment",
    )
    op.drop_index(
        op.f("ix_enrollment_policy_assignment_matricula"),
        table_name="enrollment_policy_assignment",
    )
    op.drop_index(
        op.f("ix_enrollment_policy_assignment_employee_id"),
        table_name="enrollment_policy_assignment",
    )
    op.drop_table("enrollment_policy_assignment")
    op.drop_index(
        op.f("ix_employee_holiday_calendar_assignment_holiday_calendar_id"),
        table_name="employee_holiday_calendar_assignment",
    )
    op.drop_index(
        op.f("ix_employee_holiday_calendar_assignment_employee_id"),
        table_name="employee_holiday_calendar_assignment",
    )
    op.drop_table("employee_holiday_calendar_assignment")
    op.drop_index(
        op.f("ix_work_policy_template_tenant_id"), table_name="work_policy_template"
    )
    op.drop_table("work_policy_template")
    op.drop_index(op.f("ix_time_punch_tenant_id"), table_name="time_punch")
    op.drop_index(op.f("ix_time_punch_matricula"), table_name="time_punch")
    op.drop_index(op.f("ix_time_punch_employee_id"), table_name="time_punch")
    op.drop_table("time_punch")
    op.drop_index(
        op.f("ix_time_adjustment_request_tenant_id"),
        table_name="time_adjustment_request",
    )
    op.drop_index(
        op.f("ix_time_adjustment_request_matricula"),
        table_name="time_adjustment_request",
    )
    op.drop_index(
        op.f("ix_time_adjustment_request_employee_id"),
        table_name="time_adjustment_request",
    )
    op.drop_table("time_adjustment_request")
    op.drop_index(op.f("ix_holiday_calendar_tenant_id"), table_name="holiday_calendar")
    op.drop_table("holiday_calendar")
    op.drop_index(
        op.f("ix_daily_attendance_summary_tenant_id"),
        table_name="daily_attendance_summary",
    )
    op.drop_index(
        op.f("ix_daily_attendance_summary_matricula"),
        table_name="daily_attendance_summary",
    )
    op.drop_index(
        op.f("ix_daily_attendance_summary_employee_id"),
        table_name="daily_attendance_summary",
    )
    op.drop_table("daily_attendance_summary")
    op.drop_index(
        op.f("ix_bank_hours_ledger_tenant_id"), table_name="bank_hours_ledger"
    )
    op.drop_index(
        op.f("ix_bank_hours_ledger_matricula"), table_name="bank_hours_ledger"
    )
    op.drop_index(
        op.f("ix_bank_hours_ledger_employee_id"), table_name="bank_hours_ledger"
    )
    op.drop_table("bank_hours_ledger")
    # ### end Alembic commands ###
